### ISSUE TITLE
android-native handled crashes are not reported.

### ISSUE THREAD

**Issue by jlennox** [getsentry/sentry-android#379]
_Platform:_
- [x]  Android -> compileSdkVersion: 29, targetSdkVersion: 29
- [x]  Java -> 1.8/1.8
- [x]  Kotlin -> Kotlin: 1.3.61, jvm: 1.8
- [x]  NDK -> 20.0.5594570

_IDE:_
- [x]  Android Studio -> 3.6.2

_Build system:_
- [x]  Gradle -> If yes, which version?

_Android Gradle Plugin:_
- [x]  Yes -> 3.5.3

_Sentry Android Gradle Plugin:_
- [x]  Yes -> 2.0.3

_Proguard/R8:_
- [ ]  Enabled
- [x]  Disabled

_sentry-android installed with:_
- [x] JCenter

The version of sentry-android:
**2.0.3**

---
I have the following issue:

Hi. At Discord we're looking to give Sentry a try for Android but a large bit of our codebase is NDK.

Crashes in Kotlin are captured and sent, as well as `Sentry.captureMessage` calls. However, our NDK
crashes are not.

I've enabled the `isDebug` to get a better idea of what's happening. Sentry-native appears to detect the
signal. But it seems the event is never sent, and there's no pending event inside the outbox.

I am reproducing an Android 6 specific crash using a x86 VM as well as a physical device. Both behave
identically.

Here's what I believe are the relevant logs:

> JNI DETECTED ERROR IN APPLICATION: JNI NewStringUTF called with pending exception java.lang.NoClassDefFoundError: ...

Big stack dump here from the native crash.

> 04-28 13:55:51.177 25953-26282/? I/sentry-native: capturing event from signal
> 04-28 13:55:51.181 25953-26282/? I/sentry-native: captured backtrace with 27 frames
> 04-28 13:55:51.181 25953-26282/? I/sentry-native: capturing event
> 04-28 13:55:51.181 25953-26282/? I/sentry-native: merging scope into event

The application restarts:

> 04-28 13:55:51.821 27020-27020/? D/Sentry: Auto-init: true
> 04-28 13:55:51.821 27020-27020/? I/Sentry: Retrieving auto-init from AndroidManifest.xml
 
A bunch of noise, then:

> 04-28 13:55:52.207 27020-27020/? I/Sentry: Initializing SDK with DSN: '...'
> 04-28 13:55:52.207 27020-27020/? I/Sentry: GlobalHubMode: 'true'
> 04-28 13:55:52.208 27020-27020/? D/Sentry: Scheduled sending cached files from /data/user/0/com.company_name.debug/cache/sentry
> 04-28 13:55:52.208 27020-27020/? D/Sentry: SendCachedEventFireAndForgetIntegration installed.
> 04-28 13:55:52.209 27020-27020/? D/Sentry: Scheduled sending cached files from /data/user/0/com.company_name.debug/cache/sentry
> 04-28 13:55:52.209 27020-27020/? D/Sentry: SendCachedEventFireAndForgetIntegration installed.
> 04-28 13:55:52.209 27020-27020/? D/Sentry: default UncaughtExceptionHandler class='io.sentry.core.UncaughtExceptionHandlerIntegration'
> 04-28 13:55:52.209 27020-27020/? D/Sentry: UncaughtExceptionHandlerIntegration installed.
> 04-28 13:55:52.209 27020-27020/? D/Sentry: Registering EnvelopeFileObserverIntegration for path: /data/user/0/com.company_name.debug/cache/sentry/outbox
> 04-28 13:55:52.210 27020-27020/? D/Sentry: EnvelopeFileObserverIntegration installed.
> 04-28 13:55:52.210 27020-27020/? D/Sentry: NdkIntegration enabled: true
> 04-28 13:55:52.210 27020-27020/? I/sentry-native: starting backend
> 04-28 13:55:52.210 27020-27020/? D/Sentry: NdkIntegration installed.
> 04-28 13:55:52.210 27020-27020/? D/Sentry: AnrIntegration enabled: true
> 04-28 13:55:52.212 27020-27108/? D/Sentry: Processing 0 items from cache dir /data/user/0/com.company_name.debug/cache/sentry
> 04-28 13:55:52.212 27020-27108/? D/Sentry: '/data/user/0/com.company_name.debug/cache/sentry/outbox' is not a file.
> 04-28 13:55:52.212 27020-27108/? D/Sentry: Finished processing cached files from /data/user/0/com.company_name.debug/cache/sentry
> 04-28 13:55:52.212 27020-27109/? D/Sentry: Processing 0 items from cache dir /data/user/0/com.company_name.debug/cache/sentry/outbox
> 04-28 13:55:52.212 27020-27109/? D/Sentry: Finished processing cached files from /data/user/0/com.company_name.debug/cache/sentry

Note that this is a synthetic event. 

> 04-28 13:55:52.215 27020-27020/? D/Sentry: Capturing event: 7add451d53dc4df0b73d0b1e10ce5ff7
> 04-28 13:55:52.232 27020-27106/? I/Sentry: Proguard UUIDs file not found.
> 04-28 13:55:52.240 27020-27020/? I/company_name: io.sentry.core.protocol.Message@f8b59c
> 04-28 13:55:52.242 27020-27110/? D/Sentry: Adding Event to offline storage: /data/user/0/com.company_name.debug/cache/sentry/7add451d53dc4df0b73d0b1e10ce5ff7.sentry-event

**Comment by marandaneto** [comment]
hey @jlennox thanks for raising this issue.

That's odd, we are gonna look into it now.
While we investigate this further would you mind trying out our beta version? `2.1.0-beta.2` a few fixes have been made and I just wanted to be sure that this issue exists or not also on the beta version.

Thanks and talk to you soon.

cc @Swatinem

**Comment by marandaneto** [comment]
hey @jlennox so I can't really reproduce this, we don't use `NewStringUTF` at all and the only `JNI` call is to start the native bits which were successful due logging `NdkIntegration installed`

I've tried using a Pixel 2 API 23 x86 VM too, it works using Sentry 2.0.3 and also the latest beta version.

have you called any of Sentry's functions? like `sentry_value_set_by_key`?

Thanks.

**Comment by Swatinem** [comment]
> 04-28 13:55:51.181 25953-26282/? I/sentry-native: merging scope into event

Is there more logs after that one? We recently added quite a lot more logging there. Would be nice to try with the latest version and see what that says.

**Comment by jlennox** [comment]
Thanks for the fast response everyone! I've done some more experimenting and hopefully we can figure this one out.

@Swatinem No, that is where the logs end. There is nothing of interest between the last sentry log and the process' death being announced.

@marandaneto Here are more exact reproduction steps. All new reproductions have been done on 2.1.0-beta.2. Sorry that I do not have the time today to setup an exact test project to reproduce this.

On a Nexus 4 + API 23 (Android 6) VM running this code causes a `java.lang.NoClassDefFoundError` crash:
```
    val foo = java.util.HashMap<Integer, Integer>()
    foo.forEach{ _, _ -> }
```

When this crash happens from our internal library we include via `{ dependencies { implementation ...  } }` the issue reported in my original post happens. When this crash is triggered inside the main application instead, Sentry reports as expected. Here's a new reproduction using 2.1.0-beta.2.

Program starts up.

```
04-29 09:33:11.597 6618-6618/? I/Sentry: Initializing SDK with DSN: '...'
04-29 09:33:11.597 6618-6618/? I/Sentry: GlobalHubMode: 'true'
04-29 09:33:11.597 6618-6618/? D/Sentry: Scheduled sending cached files from /data/user/0/com.company_name.debug/cache/sentry
04-29 09:33:11.598 6618-6618/? D/Sentry: SendCachedEventFireAndForgetIntegration installed.
04-29 09:33:11.602 6618-6618/? D/Sentry: Scheduled sending cached files from /data/user/0/com.company_name.debug/cache/sentry
04-29 09:33:11.602 6618-6618/? D/Sentry: SendCachedEventFireAndForgetIntegration installed.
04-29 09:33:11.602 6618-6618/? D/Sentry: default UncaughtExceptionHandler class='io.sentry.core.UncaughtExceptionHandlerIntegration'
04-29 09:33:11.603 6618-6618/? D/Sentry: UncaughtExceptionHandlerIntegration installed.
04-29 09:33:11.603 6618-6618/? D/Sentry: NdkIntegration enabled: true
04-29 09:33:11.604 6618-6618/? I/sentry-native: Using database path "/data/data/com.company_name.debug/cache/sentry/.sentry-native"
04-29 09:33:11.605 6618-6618/? I/sentry-native: starting backend
04-29 09:33:11.605 6618-6618/? D/Sentry: NdkIntegration installed.
04-29 09:33:11.605 6618-6618/? D/Sentry: Registering EnvelopeFileObserverIntegration for path: /data/user/0/com.company_name.debug/cache/sentry/outbox
04-29 09:33:11.605 6618-6618/? D/Sentry: EnvelopeFileObserverIntegration installed.
04-29 09:33:11.605 6618-6702/? D/Sentry: Processing 0 items from cache dir /data/user/0/com.company_name.debug/cache/sentry
04-29 09:33:11.605 6618-6702/? D/Sentry: File /data/user/0/com.company_name.debug/cache/sentry/outbox is not a File.
04-29 09:33:11.605 6618-6703/? D/Sentry: Processing 0 items from cache dir /data/user/0/com.company_name.debug/cache/sentry/sessions
04-29 09:33:11.605 6618-6703/? D/Sentry: Finished processing cached files from /data/user/0/com.company_name.debug/cache/sentry
04-29 09:33:11.605 6618-6702/? D/Sentry: File /data/user/0/com.company_name.debug/cache/sentry/sessions is not a File.
04-29 09:33:11.605 6618-6702/? D/Sentry: File /data/user/0/com.company_name.debug/cache/sentry/.sentry-native is not a File.
04-29 09:33:11.605 6618-6702/? D/Sentry: Finished processing cached files from /data/user/0/com.company_name.debug/cache/sentry
04-29 09:33:11.606 6618-6618/? D/Sentry: Scheduled sending cached files from /data/user/0/com.company_name.debug/cache/sentry
04-29 09:33:11.606 6618-6618/? D/Sentry: SendCachedEventFireAndForgetIntegration installed.
04-29 09:33:11.606 6618-6618/? D/Sentry: AnrIntegration enabled: true
04-29 09:33:11.606 6618-6618/? D/Sentry: SessionTrackingIntegration enabled: false
04-29 09:33:11.609 6618-6704/? D/Sentry: Processing 0 items from cache dir /data/user/0/com.company_name.debug/cache/sentry/outbox
04-29 09:33:11.609 6618-6704/? D/Sentry: Finished processing cached files from /data/user/0/com.company_name.debug/cache/sentry
04-29 09:33:11.624 6618-6701/? I/Sentry: Proguard UUIDs file not found.
```

Crashes here.

```
04-29 09:34:05.716 6618-6797/com.company_name.debug A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: JNI NewStringUTF called with pending exception java.lang.NoClassDefFoundError: co.company_name.media_engine.VoiceQuality$update$2
[big stackdump/etc removed]
04-29 09:34:06.190 6618-6797/? I/sentry-native: capturing event from signal
04-29 09:34:06.193 6618-6797/? I/sentry-native: captured backtrace with 27 frames
04-29 09:34:06.193 6618-6797/? I/sentry-native: capturing event
04-29 09:34:06.193 6618-6797/? I/sentry-native: merging scope into event
```

Actual process exit.

```
04-29 09:34:06.262 1715-1715/? I/Zygote: Process 6618 exited due to signal (11)
04-29 09:34:06.268 1990-2248/system_process I/ActivityManager: Process com.company_name.debug (pid 6618) has died
```

Program is restarted.

```
04-29 09:34:09.006 6842-6842/com.company_name.debug D/Sentry: Auto-init: true
04-29 09:34:09.006 6842-6842/com.company_name.debug I/Sentry: Retrieving auto-init from AndroidManifest.xml
[removed]
04-29 09:34:09.168 6842-6842/com.company_name.debug I/Sentry: Initializing SDK with DSN: '...'
04-29 09:34:09.168 6842-6842/com.company_name.debug I/Sentry: GlobalHubMode: 'true'
04-29 09:34:09.168 6842-6842/com.company_name.debug D/Sentry: Scheduled sending cached files from /data/user/0/com.company_name.debug/cache/sentry
04-29 09:34:09.168 6842-6842/com.company_name.debug D/Sentry: SendCachedEventFireAndForgetIntegration installed.
04-29 09:34:09.169 6842-6842/com.company_name.debug D/Sentry: Scheduled sending cached files from /data/user/0/com.company_name.debug/cache/sentry
04-29 09:34:09.169 6842-6912/com.company_name.debug D/Sentry: Processing 0 items from cache dir /data/user/0/com.company_name.debug/cache/sentry
04-29 09:34:09.169 6842-6842/com.company_name.debug D/Sentry: SendCachedEventFireAndForgetIntegration installed.
04-29 09:34:09.169 6842-6842/com.company_name.debug D/Sentry: default UncaughtExceptionHandler class='io.sentry.core.UncaughtExceptionHandlerIntegration'
04-29 09:34:09.169 6842-6842/com.company_name.debug D/Sentry: UncaughtExceptionHandlerIntegration installed.
04-29 09:34:09.169 6842-6842/com.company_name.debug D/Sentry: NdkIntegration enabled: true
04-29 09:34:09.169 6842-6912/com.company_name.debug D/Sentry: File /data/user/0/com.company_name.debug/cache/sentry/outbox is not a File.
04-29 09:34:09.169 6842-6912/com.company_name.debug D/Sentry: File /data/user/0/com.company_name.debug/cache/sentry/sessions is not a File.
04-29 09:34:09.169 6842-6912/com.company_name.debug D/Sentry: File /data/user/0/com.company_name.debug/cache/sentry/.sentry-native is not a File.
04-29 09:34:09.169 6842-6912/com.company_name.debug D/Sentry: Finished processing cached files from /data/user/0/com.company_name.debug/cache/sentry
04-29 09:34:09.170 6842-6842/com.company_name.debug I/sentry-native: Using database path "/data/data/com.company_name.debug/cache/sentry/.sentry-native"
04-29 09:34:09.171 6842-6842/com.company_name.debug I/sentry-native: starting backend
04-29 09:34:09.171 6842-6842/com.company_name.debug D/Sentry: NdkIntegration installed.
04-29 09:34:09.171 6842-6842/com.company_name.debug D/Sentry: Registering EnvelopeFileObserverIntegration for path: /data/user/0/com.company_name.debug/cache/sentry/outbox
04-29 09:34:09.171 6842-6842/com.company_name.debug D/Sentry: EnvelopeFileObserverIntegration installed.
04-29 09:34:09.172 6842-6842/com.company_name.debug D/Sentry: Scheduled sending cached files from /data/user/0/com.company_name.debug/cache/sentry
04-29 09:34:09.172 6842-6842/com.company_name.debug D/Sentry: SendCachedEventFireAndForgetIntegration installed.
04-29 09:34:09.172 6842-6913/com.company_name.debug D/Sentry: Processing 0 items from cache dir /data/user/0/com.company_name.debug/cache/sentry/sessions
04-29 09:34:09.172 6842-6842/com.company_name.debug D/Sentry: AnrIntegration enabled: true
04-29 09:34:09.172 6842-6913/com.company_name.debug D/Sentry: Finished processing cached files from /data/user/0/com.company_name.debug/cache/sentry
04-29 09:34:09.172 6842-6842/com.company_name.debug D/Sentry: SessionTrackingIntegration enabled: false
04-29 09:34:09.173 6842-6914/com.company_name.debug D/Sentry: Processing 0 items from cache dir /data/user/0/com.company_name.debug/cache/sentry/outbox
04-29 09:34:09.173 6842-6914/com.company_name.debug D/Sentry: Finished processing cached files from /data/user/0/com.company_name.debug/cache/sentry
04-29 09:34:09.194 6842-6911/com.company_name.debug I/Sentry: Proguard UUIDs file not found.
```


Now if I move that crash into my main program, Sentry performs as expected.

```
04-29 10:07:21.535 8499-8499/com.company_name.debug I/Sentry: Uncaught exception received.
04-29 10:07:21.536 8499-8499/com.company_name.debug D/Sentry: Capturing event: 4d679d41e4e14555aa3eee437bd6b011
04-29 10:07:21.544 8499-8499/com.company_name.debug I/Sentry: Not possible to read external files directory
04-29 10:07:21.545 8499-8499/com.company_name.debug I/Sentry: Session is null on scope.withSession
04-29 10:07:21.545 8499-8499/com.company_name.debug I/company_name: setBeforeSend (ignore this!) 'null'
04-29 10:07:21.546 8499-8668/com.company_name.debug D/Sentry: Adding Event to offline storage: /data/user/0/com.company_name.debug/cache/sentry/4d679d41e4e14555aa3eee437bd6b011.sentry-event
04-29 10:07:21.561 8499-8499/com.company_name.debug I/Sentry: Invoking inner uncaught exception handler.
04-29 10:07:21.561 8499-8499/com.company_name.debug D/Sentry: Capturing event: aa141976c58843b89a1876f09cfb34b0
04-29 10:07:21.562 8499-8668/com.company_name.debug D/Sentry: Disk flush event fired: 4d679d41e4e14555aa3eee437bd6b011
04-29 10:07:21.568 8499-8499/com.company_name.debug I/Sentry: Not possible to read external files directory
04-29 10:07:21.569 8499-8499/com.company_name.debug I/Sentry: Session is null on scope.withSession
04-29 10:07:21.569 8499-8499/com.company_name.debug I/company_name: setBeforeSend (ignore this!) 'null'
[removed]
04-29 10:07:32.630 8499-8668/com.company_name.debug D/Sentry: Event sent 4d679d41e4e14555aa3eee437bd6b011 successfully.
04-29 10:07:32.630 8499-8668/com.company_name.debug D/Sentry: Discarding event from cache: /data/user/0/com.company_name.debug/cache/sentry/4d679d41e4e14555aa3eee437bd6b011.sentry-event
04-29 10:07:32.630 8499-8668/com.company_name.debug D/Sentry: Event flushed: 4d679d41e4e14555aa3eee437bd6b011
04-29 10:07:32.630 8499-8668/com.company_name.debug D/Sentry: Adding Event to offline storage: /data/user/0/com.company_name.debug/cache/sentry/aa141976c58843b89a1876f09cfb34b0.sentry-event

    --------- beginning of crash
04-29 10:07:32.632 8499-8499/com.company_name.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.company_name.debug, PID: 8499
    java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.NoClassDefFoundError: com.company_name.app.foo$bar$1
[removed]
04-29 10:07:32.633 8499-8668/com.company_name.debug D/Sentry: Disk flush event fired: aa141976c58843b89a1876f09cfb34b0
[removed]
04-29 10:07:36.200 8499-8668/com.company_name.debug D/Sentry: Event sent aa141976c58843b89a1876f09cfb34b0 successfully.
04-29 10:07:36.200 8499-8668/com.company_name.debug D/Sentry: Discarding event from cache: /data/user/0/com.company_name.debug/cache/sentry/aa141976c58843b89a1876f09cfb34b0.sentry-event
04-29 10:07:36.200 8499-8668/com.company_name.debug D/Sentry: Event flushed: aa141976c58843b89a1876f09cfb34b0
```

**Comment by marandaneto** [comment]
@jlennox thanks for the detailed message, yes a test project would be great, let's see if we can find out without it for now.

I just wanted to ask if you call any method from `sentry.h` ? and if so, which ones?
if you are just doing a segfault, how are you causing that? that would help to reproduce it I guess, thanks :)

**Comment by jlennox** [comment]
@marandaneto There are no calls or references to `sentry.h`.

The crash was caused by that previously pasted Kotlin code, because it's using a Java feature not available on Android 6.

**Comment by marandaneto** [comment]
@jlennox I'm a bit lost here, your original code mentions sentry-native, NDK, also that Crashes in Kotlin are captured and sent.

But now you say that the crash was caused by the posted Kotlin code, which is not a C/C++ code and it's never sending them.

Could you clarify what exactly are you doing and trying to achieve? thanks :)

**Comment by marandaneto** [comment]
also, I don't see how this Kotlin code can cause a `SIGSEGV`, it should only be the case of triggering an `UncaughtExceptionHandler`, that's odd, we'd need more info so we could try to reproduce it again.

<img width="902" alt="Screenshot 2020-04-29 at 21 51 22" src="https://user-images.githubusercontent.com/5731772/80640452-b3bb1880-8a63-11ea-845a-12ebdcb2ba59.png">

**Comment by marandaneto** [comment]
hey @jlennox just wanted to be sure that you were not left alone, did you have the time to investigate a bit about it? we'd love to learn more about it.

**Comment by jlennox** [comment]
@marandaneto Thanks for checking in! I'm currently handling a different task but will be back on this next week sometime. I'll make an isolated reproduction so that you guys will have something to execute locally.

My current assumption is that when the Java exception is triggered from inside a .so the issue reproduces, but I have not tested that assumption.

**Comment by marandaneto** [comment]
@jlennox I see, yeah that's odd, we'll be waiting for your reproducible repo then, thanks a lot for this.

**Comment by jlennox** [comment]
@marandaneto I wont have time again to create an isolated reproduction, largely because I am not much of an Android developer so there's a large learning curve. But I believe the situation happens when a Java exception is triggered inside a dynamic library (.so). Does that make sense?

**Comment by marandaneto** [comment]
hey @jlennox thanks for the message.

It does, just to confirm that I'll write a pseudo-example and you double-check it.

App. starts.
App. inits Sentry.
App. loads a dynamic lib (lets call native-lib).
App. calls a native method which is in the native-lib thru JNI (Java/Kotlin -> C/C++).
the native-lib happens to call a Java/Kotlin method thru JNI which happens to throw an exception (C/C++ -> Java/Kotlin) on the Java/Kotlin layer.

Is that right? thanks a lot :)

**Comment by jlennox** [comment]
@marandaneto Yes that is exactly it. The exception we were hitting was Kotlin code that used `Map.forEach(x, y ->` syntax which was not available on Android 6 and lower.

**Comment by marandaneto** [comment]
got it, @jlennox last question, did the Kotlin method called thru JNI from native code had a return value? and if so, did the return value was used?

eg:
```
fun kotlintest(): String {
  //throw
  return ""
}
```

```
void nativetest() {
  jobject test = jni.kotlintest();
  // did we use test here?
}
```

**Comment by jlennox** [comment]
@marandaneto The method signature was `(Ljava/lang/String;)V`

**Comment by marandaneto** [comment]
I think I've been able to reproduce it and this one is gonna be a tough one, very good catch @jlennox thanks for reporting this.

See: https://github.com/getsentry/sentry-android/pull/443
cc @Swatinem Let's discuss this next week.

**Comment by Swatinem** [comment]
@marandaneto did a really nice analysis, and we discussed this right now real quick. So, we *think* this is whats happening:

* You are calling Java via JNI from inside a dynamically loaded `.so`
* Java throws
* 1. The uncaught exception handler runs on the java side
* 2. The JNI call still returns, but with `NULL`
* Native produces a segfault, because of the `NULL`
* both the uncaught exception handler, and the native signal handler are running
* the java runtime (probably) kills the native code, sending a SIGQUIT
* for whatever reason, none of the two handler actually complete in logging the exception.

This is a really complex case. We will try to discuss this further internally, and see if we can think of a solution to this.

**Comment by marandaneto** [comment]
hey sorry for the late reply here, I could not reproduce this issue anymore using the latest stable version of the Android SDK, this issue has probably been fixed along with other fixes on the `sentry-native` branch.

@jlennox please upgrade the SDK to the last stable version and let us know if you still experience this issue, thanks for reporting this and the patience.
